# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b3c7324323f41406fa804a2daed81e33108ea1a81dc19be6058d0f59060c5955e23c12f538e933eac9734dbac7eba91538fd861d763c3647a3f756748ebf5b8

test:
  secret_key_base: 0a4816fae5fb2b071d90c6e42567f8b411217dea114ffa7ebfdf50a53747f9130bdc6d35a164f682b69fd03c99a9d9135c1a060c9106c5361ccc3b2c218705b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
